#!/bin/sh
user=$1
repo=$2
tag=$3
folder=$4
echo user=$user
echo repo=$repo
echo tag=$tag
echo folder=$folder

for f in $folder; do
    echo tools/bin/linux/amd64/github-release upload --user $user --repo $repo --tag $tag --file $f
    tools/bin/linux/amd64/github-release upload --user $user --repo $repo --tag $tag --name $(basename $f) --file $f
done

